title: Imgbrd-Grabber
subtitle: Booru browsing made easy
description: Very customizable imageboard/booru browser and mass downloader, with powerful filenaming features.
logo: assets/img/icon.png
show_download: true
google_analytics:
theme:
lang: en_US

exclude:
- release/
- releases/
- cli/build/
- gui/build/
- tests/build/

gems:
- jekyll-seo-tag

webmaster_verifications:
  google: HUsU9v5lhoPPeKdafhViSRi1NofQwzQrRwLN1nEzsA8

defaults:
  - scope:
      path: ""
    values:
      image: assets/img/icon.png